import Logos from "./Logo";

const SkillsData = [
	{ name: "API", logo: Logos.ApiLogo },
	{ name: "Bootstrap", logo: Logos.BootstrapLogo },
	{ name: "CSS", logo: Logos.CssLogo },
	{ name: "Express", logo: Logos.ExpressLogo },
	{ name: "Figma", logo: Logos.FigmaLogo },
	{ name: "Git", logo: Logos.GitLogo },
	{ name: "HTML", logo: Logos.HtmlLogo },
	{ name: "Javascript", logo: Logos.JavascriptLogo },
	{ name: "Jquery", logo: Logos.JqueryLogo },
	{ name: "MongoDB", logo: Logos.MongodbLogo },
	{ name: "MySQL", logo: Logos.MysqlLogo },
	{ name: "Node", logo: Logos.NodeLogo },
	{ name: "NPM", logo: Logos.NpmLogo },
	{ name: "React", logo: Logos.ReactLogo },
	{ name: "Tailwind", logo: Logos.TailwindLogo },
	{ name: "Typescript", logo: Logos.TypescriptLogo },
	{ name: "VSCode", logo: Logos.VscodeLogo },
	{ name: "Webpack", logo: Logos.WebpackLogo },
	{ name: "Vite", logo: Logos.ViteLogo },
	{ name: "Mongoose", logo: Logos.MongooseLogo },
	{ name: "Redux", logo: Logos.ReduxLogo },
	{ name: "PWA", logo: Logos.PwaLogo },
	{ name: "Photoshop", logo: Logos.PhotoshopLogo },
	{ name: "Illustrator", logo: Logos.IllustratorLogo },
	{ name: "GraphQL", logo: Logos.GraphqlLogo },
	{ name: "Nextjs", logo: Logos.NextjsLogo },
	{ name: "Jest", logo: Logos.JestLogo },
	{ name: "Heroku", logo: Logos.HerokuLogo },
	{ name: "Handlebars", logo: Logos.HandlebarsLogo },
	{ name: "Sequelize", logo: Logos.SequelizeLogo },
];

export default SkillsData;
